{% set name = "rang" %}
{% set version = "3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/agauniyal/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 8b42d9c33a6529a6c283a4f4c73c26326561ccc67fbb3e6a3225edd688b39973

build:
  number: 0

requirements:
  build: []
  host: []

test:
  commands:
    - test -f ${PREFIX}/include/rang.hpp           # [unix]
    - if not exist %LIBRARY_INC%\rang.hpp exit 1   # [win]

about:
  home: https://github.com/agauniyal/rang
  license: Unlicense
  license_family: OTHER
  license_file: LICENSE
  summary: 'Colors for your Terminal.'
  description: |
    rang only depends on C++ standard library, unistd.h system header on unix and 
    windows.h & io.h system headers on windows based systems. In other words, you 
    don't need any 3rd party dependencies.
  dev_url: https://github.com/agauniyal/rang

extra:
  recipe-maintainers:
    - marcelotrevisani
    - ngam
