travis:
  secure:
    BINSTAR_TOKEN: SPjSBNOUgy9tMCdRF+UTvMejrR0B6P2xvIf4mPrX/SNBbVl9N6Xgvhnom3RYtOS8zuRjFc/pq74H7pK5uGfRDP4Rluyt8v6cP458KPsRzHQgJoVI9tx20yr3GibQykLbpQqBq21r6dxrCOSapDo9vMYQMUAvBK+wHhmYYQpmZmzxxEUKuYBtbYQKM9vpchF3sd1RfRay6vA4PVKDC4FM/ar/YWjeV/rmiKr8rZNxtgp9vx+2B6jXF8NK5dTiThpcNEVRBWFUQPG95C2AABQE+3tX5tqbMaEZxcYQdAsBhJ4f6cY9iIi6LgtCbmAlUW3jbwlrWwyeQoy54knlWZHzIWb3ooOlaArLBljLRF8YDMi9e6k6/dXsoM1RGx5Ktvzm9WyePfs3OkvhyMTjnHO4FTV4i2w4kOvKIans01WvicCF80Xb7bgjm29JeMtEKQABSbQDG22hOiE/i1SQOJHaS4aZmYan/7JGH/1Dkthi0w4Nn+GXuoFgrT15KT8EdpdeWX2BJ2R8LYF+JGKN5cMdhhFW9rbFTIQg4w9SoVwVyy+sS5movxRLUkJBnJVfb42BH1FBOmjptz00tup/Ej36OBVAy13jplMeV7SCU8LIMlGwNlCUp8dfMkrNM4xFtYKLhkATIchiXGWF7FKo1AcumLFGs/7OWBdsW7voZU1sF2k=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
conda_forge_output_validation: false
